### PR TITLE
Adding FFMpeg QSV codecs

### PR DESCRIPTION
**Pull request by MathewSachin**
Implementing Hardware Acceleration using FFMpeg on Intel Quick Sync Video.

- `h264_qsv` codec does not seem useful as `libx264` with `ultrafast` preset seems equivalent or even more faster.
- `hevc_qsv` is really great in terms of CPU usage as compared to `libx265`.

ffmpeg.exe must be built using `--enable-libmfx` option. Zeranoe builds are fine.

Special thanks to @AlexAlabyev for suggesting and guiding on this feature in #69.

## ToDo
Show error when QSV isn't supported.

### CODE REVIEW

**Comment by AlexAlabyev** [comment]
@MathewSachin hey good job! You can send me the link for the build, I'll test it.

**Comment by MathewSachin** [comment]
Here's it: https://ci.appveyor.com/api/buildjobs/5fmm76fmx4d3rfg6/artifacts/Output%2FCaptura-Release.zip

The new HEVC QSV encoder in the FFMpeg encoders list.

**Comment by AlexAlabyev** [comment]
@MathewSachin hmm, for some reason it doesn't save files when you record with any ffmpeg format. When I click stop recording, it shows a notification and when you click it, "An error occured" window pops up saying "Could not find file". And if you click record again it will show this another IO error until you restart the program:
screenshot 533

**Comment by MathewSachin** [comment]
I've done a fix regarding the codecs requiring even video dimensions, please try https://ci.appveyor.com/api/buildjobs/mtbq2aidj90lbmyl/artifacts/Output%2FCaptura-Release.zip

**Comment by AlexAlabyev** [comment]
@MathewSachin okay, HEVC x265 saves videos now, but still no luck with HEVC IntelQSV, it's the same error on both CPUs  (one with IntelQSV support and the other one without IntelQSV support, same error).

Also, I noticed that HEVC x265 is having problems syncing system audio with video and it has high CPU usage when recording.

**Comment by AlexAlabyev** [comment]
@MathewSachin do you know what can cause this IntelQSV error?

**Comment by MathewSachin** [comment]
IntelQSV is working on my system. I'm planning to remove HEVC x265 due to that high CPU usage.
We'll have to research more.

**Comment by MathewSachin** [comment]
It is working most of the time on my laptop.

Here's a video for proof:
[2017-07-01-15-00-36.zip](https://github.com/MathewSachin/Captura/files/1116959/2017-07-01-15-00-36.zip)

**Comment by AlexAlabyev** [comment]
@MathewSachin here's the log for HEVC IntelQSV.  
Captura.exe 24% CPU usage (i7 8 threads), 50mb RAM
ffmpeg.exe  doesn't run

### Log
```
ffmpeg version N-86383-g4705edb Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-cuda --enable-cuvid --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-zlib
  libavutil      55. 63.100 / 55. 63.100
  libavcodec     57. 96.101 / 57. 96.101
  libavformat    57. 72.101 / 57. 72.101
  libavdevice    57.  7.100 / 57.  7.100
  libavfilter     6. 91.100 /  6. 91.100
  libswscale      4.  7.101 /  4.  7.101
  libswresample   2.  8.100 /  2.  8.100
  libpostproc    54.  6.100 / 54.  6.100
Unrecognized option 'init_hw_device'.
Error splitting the argument list: Option not found

```

**Comment by AlexAlabyev** [comment]
Also, what about CPUs that doesn't support IntelQSV? Maybe put a warning there, saying that only Haswell CPUs and above support HEVC IntelQSV? Or maybe even add a checking function to hide the option if it's not supported on CPU. Maybe something like [this](https://github.com/jp9000/obs-studio/search?utf8=%E2%9C%93&q=haswell&type=). But I suppose it'll take more time to implement, so maybe a warning will do for now?

**Comment by MathewSachin** [comment]
I checked OBS, they are using ffmpeg as library not as ffmpeg.exe

Your error log says that an option is not recognized. Maybe using a new version would fix that: https://ffmpeg.zeranoe.com/builds/

**Comment by MathewSachin** [comment]
We cannot currently use FFMpeg as a library to mainain the MIT License. Else we will have to switch to GPL but I'm reluctant to.

**Comment by AlexAlabyev** [comment]
@MathewSachin yep, I had to download ffmpeg and specify **bin** folder in Captura, now it saves the videos. I suppose the ffmpeg in the build you sent me wasn't the newest one?
I've downloaded this one:
image

**Comment by MathewSachin** [comment]
@AlexAlabyev In the latest release v4.2.0 there is a fix for the high CPU usage of Captura.
Please test the release.

**Comment by AlexAlabyev** [comment]
@MathewSachin yeah, ffmpeg has been working without me even specifying the ffmpeg folder in Captura, so I thought ffmpeg.exe was included. I forgot I've installed it --globally a few months ago.

I've tested the latest release:
### ffmpeg | mp4
- 1080p & 768p screens | [window]-[desktop]
CPU <5% | RAM <160mb

### ffmpeg | hevc
- not an option

### gif | gif | 30fps 100q
- 1080p screen | [window]-[desktop]
CPU <26% | RAM usage goes to 3,5GB and crash
- 1080p screen | [region]-[Region Selector]
CPU <20% | RAM <80mb

- 768p screen | [window]-[desktop]
CPU <20% | RAM <80mb
- 768p screen | [region]-[Region Selector]
CPU <20% | RAM <80mb

**Comment by MathewSachin** [comment]
The 3.5GB crash you mentioned is currently an open issue: #60.

As a fix, try enabling **Variable Frame Rate** option in **Config** tab.

**Comment by AlexAlabyev** [comment]
@MathewSachin yep, that fixes **gif | gif**, but it doesn't affect **ffmpeg | gif** and it uses a lot of memory when you choose high frame rate. Also **ffmpeg | gif** creates a very bad quality gifs, maybe it's better disable it and leave only **gif | gif**?

**Comment by MathewSachin** [comment]
I'm not currently disabling **ffmpeg | gif**, but would do in future if I won't be able to improve it.

**Comment by AlexAlabyev** [comment]
@MathewSachin agree, more options is always better, but at this moment it's not handling color blending correctly, just record Task manager with **ffmpeg | gif** and compare it to **gif | gif,** at 100q

**Comment by MathewSachin** [comment]
Sorry @AlexAlabyev I was unable to view the difference on my system. But, it is happening on your system means it can happen on other's too. So, it is an issue.

Just to note, I have not implemented the Quality option for Gifs.

**Comment by AlexAlabyev** [comment]
@MathewSachin that's strange, well I added images above, take a look. See how it blends yellow color there? It happens on my both computers with 3 different ffmpeg versions. And when you start recording a big screen region (1080p) it starts to use a lot of memory (crashes at 3GB - 5GB RAM captura.exe usage)

**Comment by MathewSachin** [comment]
OK. Now, I see that.

**Pull request merged**
