### PR TITLE
Thin Region Selector

### PR DESCRIPTION
**Pull request by MathewSachin**
Implementing a thinner Region Selector.
Lots of work to do!

#### To Do

- [x] Basic UI
- [x] fix captured Region
- [x] fix Snap to Window
- [x] Resizing using border
- [x] Lower opactiy of controls when not mouse over
- [x] move size boxes below main controls on small region size
- [x] remove `Hide during Recording` option.
- [x] low opacity of size boxes during recording.
- [x] low opacity animation.

#### First Look

First Look

### CODE REVIEW

**Comment by MathewSachin** [comment]
@Godly75
Please check this build for new Region selector: https://ci.appveyor.com/api/buildjobs/twah80tvxo04f9yb/artifacts/Captura-Portable.zip

**Comment by Godly75** [comment]
way way beter !!!! :)
I love it ! This app has become so much more valuable the last days ! 
It's gonna be my nr1 app for screenshots.

**Comment by Godly75** [comment]
Suggestions to the video region recording:
- maybe add the magnifier to the video region selection also?
- add the screen size pixels notification the same as in the screenshots (instead of the right bottom corner)
- add big countdown notification on the delayed start

**Comment by MathewSachin** [comment]
> maybe add the magnifier to the video region selection also?

No, this can't be done because while the magnifier is shown, user cannot work with other apps.

> add the screen size pixels notification the same as in the screenshots (instead of the right bottom corner)

It's not a notification but those text boxes can be used to changed size. I think they should not be put between the region where user might want to do his work.

> add big countdown notification on the delayed start

Not big, but I added countdown in place of Duration on delayed start.
The `Start Delay` setting has changed to `Pre-Start Countdown` and is now specified in **seconds**.
It will be shown on both Main UI and Region selector.
Please test: https://ci.appveyor.com/api/buildjobs/ux6hwho7h3njfl8d/artifacts/Captura-Portable.zip

**Comment by Godly75** [comment]
Works perfect ! I was thinking to see it big in the middle of the screen, but this works also :)

**Pull request merged**
