### PR TITLE
make window source working in console mode

### PR DESCRIPTION
**Pull request by hyunjong-lee**
working console windows mode recording ...

### CODE REVIEW

**Comment by MathewSachin** [comment]
@hyunjong-lee Thank you for your willingness to contribute 👍.

I've confirmed that console windows mode recording was not working in my code.

#### Problem
This pull request fixes that but now recorded window cannot be changed once it is set when recording using UI.

#### Solution
The solution I'm thinking of is to modify the `FakeVideoSourcePicker` like what we do with `FakeRegionProvider`.

I'll be happy if you're willing to take this up.

#### Related
I also think that this problem might be happening with recording a specific screen.

**Comment by hyunjong-lee** [comment]
@MathewSachin Got it, I will change as you mentioned, and then will update this PR.

**Comment by hyunjong-lee** [comment]
@MathewSachin I changed them while their variable meaning does not feat with the names. 🤣

**Comment by MathewSachin** [comment]
@hyunjong-lee I'm sorry but what you did is not exactly right.
If you're having trouble with this, I can take it up.

**Comment by hyunjong-lee** [comment]
@MathewSachin Got it! Thank you!

**Pull request closed without merging**
