### PR TITLE
Command-line support

### PR DESCRIPTION
**Pull request by MathewSachin**
See the specification: https://mathewsachin.github.io/Captura/CmdLine/

## ToDo
- Check for any possible issues with this approach in Chocolatey.
- Implement More arguments.
- Support specifying filename for the captured file.
- Testing

### CODE REVIEW

**Comment by randomwalk1225** [comment]
Really awesome. Thanks you guys really appreciate.

**Comment by MathewSachin** [comment]
Thank You @randomwalk1225.
Any suggestions you have are also welcome!

**Comment by randomwalk1225** [comment]
Can I start record, pause, stop video with command line?

**Comment by MathewSachin** [comment]
Currently pausing has not been implemented. You can start and stop recording.

Here's a dev build to test: https://ci.appveyor.com/api/buildjobs/5w2h4x69m9he481g/artifacts/Output%2FCaptura-Release.zip

Please see the specification above.

e.g. Record 20 seconds
```
captura start --length 20
```

**Pull request merged**
