### PR TITLE
es-AR locale

### PR DESCRIPTION
**Pull request by KNTRO**
**Mathew**,

Hi! Here's the _Español (Argentina) [Spanish (Argentina)]_ locale.

I can't tell if they are big differences with the _Español (México)_ locale since I'm not able to make it work. :sob:

Kind regards.

### CODE REVIEW

**Comment by MathewSachin** [comment]
Thank you @KNTRO for the work. 👍

**Just a thing to fix:**
The original Resources.resx file is not to be renamed. A copy is to be created with name as `Resources.es-AR.resx`.
Also, there are values for Width and Height (of window) in the resources. Please ensure that the window is big enough.
Once, this is done, we are good to merge.

**Comment by MathewSachin** [comment]
Hi @KNTRO. If you are experiencing any problems, let me know. I can merge the changes myself if you want. I'll make sure you get the credit.

**Comment by KNTRO** [comment]
@MathewSachin Hello Mathew.

Sorry for not reply previously —I have been a little busy.

Could you do that for me? I would thank you so much, since as you can imagine, I'm not a GitHub ace when it comes to work with some repositories. :sweat_smile:

I will very, very much appreciate it. Really.

Kind regards. :+1:

**Comment by MathewSachin** [comment]
Fine, would do it ASAP.

**Comment by KNTRO** [comment]
Thanks a lot, @MathewSachin! :clap: :clap: :clap: :clap: :clap:

**Pull request merged**
