### PR TITLE
fixed some spelling mistakes

### PR DESCRIPTION
**Pull request by trhgquan**
well, my mistakes when misunderstanding some items. now i fixed that.

_and by the way, how can i use Captura for streaming on YouTube?_

### CODE REVIEW

**Comment by MathewSachin** [comment]
An option for Streaming to YouTube Live is present but not tested.

First, set your YouTube Live key at `Configure / FFmpeg`.
Then select `Streaming > YouTube Live` as video writer.

FFmpeg is used for streaming. I'm not sure if it would work, but if you are able to please let me know.

**Comment by trhgquan** [comment]
well it doesn't work until now. but it does well on Twitch. so strange.

**Comment by MathewSachin** [comment]
One more thing to try.

There's a custom size option for FFmpeg.

Try setting it to one of the standard sizes like: 720p i.e. 1280x720.

I've heard that YouTube requires use of standard sizes.

**Comment by MathewSachin** [comment]
One more thing, someone posted that audio was required for them to stream to YouTube live.

**Comment by trhgquan** [comment]
let me try it. thanks for your help.
and also i found a bug and i submitted a new issue.

**Pull request merged**
